// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function parsePassport(param) {
  
}

function countPassport(param) {
  return 0;
}

exports.parsePassport = parsePassport;
exports.countPassport = countPassport;
/* No side effect */
