// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodefs = require("node:fs");

var input = Nodefs.readFileSync("input/Week1/Year2020Day3.sample.txt", {
      encoding: "utf8"
    });

console.log(input);

exports.input = input;
/* input Not a pure module */
