// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Js_math = require("rescript/lib/js/js_math.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var input = Fs.readFileSync("input/Week1/Year2020Day3.txt", "utf8");

function parser(str) {
  return str.trim().split("\n");
}

function contains(str, index, $$char) {
  if (str.length === 0 || index < 0 || index > str.length || $$char === "") {
    return false;
  } else {
    return str.charAt(index) === $$char;
  }
}

function executor(arr, x, y) {
  return Belt_Array.reduceWithIndex(arr, 0, (function (matchCnt, item, index) {
                if (index > 0 && Caml_int32.mod_(index, y) === 0 && contains(item, Caml_int32.mod_(Math.imul(x, Js_math.floor_int(Caml_int32.div(index, y))), item.length), "#")) {
                  return matchCnt + 1.0;
                } else {
                  return matchCnt;
                }
              }));
}

var parsedInput = input.trim().split("\n");

console.log(contains("#..##..#...##............#..##.", 3, "#"));

console.log(contains("#..##..#...##............#..##.", 0, "#"));

console.log(contains("#..##..#...##............#..##.", 3, "#"));

console.log(contains("#..##..#...##............#..##.", 4, "#"));

console.log(contains("#..##..#...##............#..##.", 5, "#"));

console.log(Belt_Array.get(parsedInput, 1));

console.log(Belt_Array.get(parsedInput, 322));

console.log(executor(parsedInput, 1, 1));

console.log(executor(parsedInput, 3, 1));

console.log(executor(parsedInput, 5, 1));

console.log(executor(parsedInput, 7, 1));

console.log(executor(parsedInput, 1, 2));

console.log(executor(parsedInput, 1, 1) * executor(parsedInput, 3, 1) * executor(parsedInput, 5, 1) * executor(parsedInput, 7, 1) * executor(parsedInput, 1, 2));

exports.input = input;
exports.parser = parser;
exports.contains = contains;
exports.executor = executor;
exports.parsedInput = parsedInput;
/* input Not a pure module */
